name: Deploy cekulit-auth to Cloud Run

on:
  push:
    branches:
      - auth
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/cekulit-auth:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/cekulit-auth:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cekulit-auth \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cekulit-auth:${{ github.sha }} \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated \
            --set-env-vars "NODE_ENV=production,EMAIL_USER=${{ secrets.EMAIL_USER }},EMAIL_PASS=${{ secrets.EMAIL_PASS }},BUCKET_NAME=${{ secrets.BUCKET_NAME }}" \
            --service-account ${{ secrets.GCP_SA_EMAIL }}